name: Santos Magic Studio
favicon: null
layout_spectrum: 0.97652
typography_spectrum: 0.59988
title: La Magía de Mercadear con Video
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#c4c4c4'
    - '#555555'
    - '#f69326'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
