name: Santos Magic Studio
favicon: null
layout_spectrum: 0.97652
typography_spectrum: 1
title: La Magía de Mercadear con Video
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffef1'
    - '#eab977'
    - '#6d5a53'
    - '#1e0000'
    - '#f8290a'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
