name: Santos Magic Studio
favicon: null
layout_spectrum: 0.95003
typography_spectrum: 0.62372
title: La Magía de Mercadear con Video
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
